use_frameworks!

target 'TFSwiftKit_Example' do
  pod 'TFSwiftKit', :path => '../'

  target 'TFSwiftKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
